### ISSUE TITLE
用了生成的ip，clone速度减少一半多。只有15k

### ISSUE THREAD

**Issue by fy8207345** [zzh-blog/GithubSpeedUp#1]

**Comment by zzh-blog** [comment]
>只有15k
？？？
没看懂，不过好用就好

**Comment by Rikka-Sei** [comment]
额，请问你所在的省份？

**Comment by Rikka-Sei** [comment]
有可能是没有检查IP的原因，我更新一下代码

**Comment by fy8207345** [comment]
> 额，请问你所在的省份？

陕西省西安市，移动。谢谢了

**Comment by zzh-blog** [comment]
可以提供一下你生成的Hosts数据吗？

**Comment by zzh-blog** [comment]
把这一条去掉，网页访问依然加速，clone走本地dns
>52.74.223.119 github.com

**Comment by Rikka-Sei** [comment]
事实证明......
![image](https://user-images.githubusercontent.com/36284614/77055216-78acda80-6a0b-11ea-94b6-fb2d2f202879.png)

我知道原因了，我去看看github有没有cdn快一点

**Comment by Rikka-Sei** [comment]
13.250.177.223 github.com 测试一下

![image](https://user-images.githubusercontent.com/36284614/77057353-c840d580-6a0e-11ea-8432-1672738bd8e0.png)

**Comment by fy8207345** [comment]
> 13.250.177.223 github.com 测试一下
> 
> ![image](https://user-images.githubusercontent.com/36284614/77057353-c840d580-6a0e-11ea-8432-1672738bd8e0.png)

这个ip可以，clone速度500多

**Comment by Rikka-Sei** [comment]
我更新了代码，可以帮我测试一下现在获取的IP是不是13.250.177.223吗？

**Comment by fy8207345** [comment]
不是，是52.74.223.119

**Comment by zzh-blog** [comment]
请问是否重新克隆了代码？我使用陕西西安的一个ip测试测试了一下，获取到了113.96.13.15

http://119.29.29.29/d?dn=www.dnspod.cn.&ip=124.115.6.19

**Comment by zzh-blog** [comment]
我是用 https://www.ip.cn/ 做接口来获取本机地址的

**Comment by zzh-blog** [comment]
![image](https://user-images.githubusercontent.com/36284614/77081675-f259be00-6a35-11ea-9036-4694ac89124b.png)

**Comment by Rikka-Sei** [comment]
谢谢，打扰了

**Comment by fy8207345** [comment]
py文件第一行加一句：#encoding=utf8

**Comment by Rikka-Sei** [comment]
> py文件第一行加一句：#encoding=utf8

为什么呢？这不是文件编码指定吗？好像不需要指定啊，在Windows，Linux，Mac都试过了

我加一下，谢谢提醒

**Comment by fy8207345** [comment]
不加的话，执行的时候提示有无法识别的字符 '\x'；我两台电脑都是这样

**Comment by Rikka-Sei** [comment]
> 不加的话，执行的时候提示有无法识别的字符 '\x'；我两台电脑都是这样

更改好了

**Comment by lain-github** [comment]
问题解决是不是close一下, 要不看issues全是open的, 哈哈.

**Comment by Rikka-Sei** [comment]
> 问题解决是不是close一下, 要不看issues全是open的, 哈哈.

OK
