### ISSUE TITLE
Windows不需要Python等第三方依赖使用脚本

### ISSUE THREAD

**Issue by bajins** [zzh-blog/GithubSpeedUp#3]
https://www.bajins.com/files/%E8%AE%BE%E7%BD%AEGitHub%E7%9A%84Hosts.bat

**Comment by Rikka-Sei** [comment]
好吧，其实我把主程序打包成exe也是可以的

**Comment by Rikka-Sei** [comment]
我已经发布exe版本了

**Comment by bajins** [comment]
7.6M...... 而且还是zip，还是脚本用着舒服

**Comment by Rikka-Sei** [comment]
你知道Linux是自带Python的吗（可尴尬了）Python顺手就用Python了......话说，我把你的脚本添加到README可以吗？可以提供一下仓库地址吗？

**Comment by bajins** [comment]
> 你知道Linux是自带Python的吗（可尴尬了）Python顺手就用Python了......话说，我把你的脚本添加到README可以吗？可以提供一下仓库地址吗？

liunx 还不如用shell脚本，以前有仓库，后来删了，我以前也是用python实现的，但是后面发现太累赘，就用的batch+Jscript实现的，也可以用powershell实现，Jscript可以见这里https://www.bajins.com/System/WindowsJScript.html

**Comment by Rikka-Sei** [comment]
嗯，说道也是，但是只是一个工具而已，实现技术上不必深究了，我认为这个工具自用已经够了。多谢

**Comment by zzh-blog** [comment]
![image](https://user-images.githubusercontent.com/36284614/77385203-6b546f00-6dc2-11ea-9652-37be3b223f09.png)
鄙人才学不足

**Comment by Rikka-Sei** [comment]
![image](https://user-images.githubusercontent.com/36284614/77385252-8d4df180-6dc2-11ea-80f4-90f14c798562.png)

匪夷所思

**Comment by bajins** [comment]
> ![image](https://user-images.githubusercontent.com/36284614/77385252-8d4df180-6dc2-11ea-80f4-90f14c798562.png)
> 
> 匪夷所思

文件格式问题，之前不小心用了unix格式
