### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by exinyu** [zzh-blog/GithubSpeedUp#4]
Traceback (most recent call last):
  File "GSU.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Python 3.6.8  + Centos 7.7

**Comment by exinyu** [comment]
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py 
pip install requests

done

**Comment by Rikka-Sei** [comment]
抱歉，没有提前说明

pip install requests
