### ISSUE TITLE
获取到的IP一个都ping不通啊伙计

### ISSUE THREAD

**Issue by jiftle** [zzh-blog/GithubSpeedUp#6]
获取到的IP一个都ping不通啊伙计

**Comment by zzh-blog** [comment]
问题是你在哪啊？

**Comment by zzh-blog** [comment]
不用具体，省份即可

**Comment by jiftle** [comment]
呵南

**Comment by zzh-blog** [comment]
![image](https://user-images.githubusercontent.com/36284614/79041680-2cc50e00-7c24-11ea-8219-10a00920b3fc.png)
可以使用
