### ISSUE TITLE
能不能换成 https://www.ipaddress.com/ 的 ip

### ISSUE THREAD

**Issue by RuytzzZ** [zzh-blog/GithubSpeedUp#7]
你这个是不是直接去腾讯dns 拿IP？ 你这 该不行还是不行啊  照样被投毒ip

**Comment by zzh-blog** [comment]
然鹅ipaddress丢给我的IP一个都用不了

**Comment by zzh-blog** [comment]
我在南京，有时候不用这个项目clone速度照样到5mb/s 我认为已经够用了，至于ipaddress的适配，你来实现一下吧，我初三，时间不多。

**Comment by zzh-blog** [comment]
顺便一提，ip投毒是不严谨的叫法，真实情况不是gfw有意要屏蔽github，而是github的各个cdn的ip不能及时被dns服务器获取，导致区域性dns服务器解析使用缓存数据，这样才导致访问缓慢。

**Comment by RuytzzZ** [comment]
> 顺便一提，ip投毒是不严谨的叫法，真实情况不是gfw有意要屏蔽github，而是github的各个cdn的ip不能及时被dns服务器获取，导致区域性dns服务器解析使用缓存数据，这样才导致访问缓慢。

那你是没遇见解析回来的ip 是gfw马甲的情况

**Comment by zzh-blog** [comment]
哦，好的，明白了
